### ISSUE TITLE
Blog: Offline-first Recipes for service workers

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#10]
Caching and offline-first recipes for cooking with Service Workers.

- [x] Define recipes to feature

@darkwing author?
- [x] Yes?

**Comment by digitarald** [comment]
@darkwing @brendandahl - should we collect a best of from the prior art resources and make them recipe-ready with more documentation?

**Comment by darkwing** [comment]
What are "prior art resources"?

**Comment by digitarald** [comment]
https://github.com/mozilla/serviceworker-cookbook#similar-projects--prior-art

**Comment by darkwing** [comment]
Draft is presently in the Hacks wordpress instance

**Comment by brendandahl** [comment]
https://hacks.mozilla.org/2015/11/offline-service-workers/
