### ISSUE TITLE
Blog: Web Push updates to the masses

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#11]
Bring delicious updates to your users with these recipes for cooking with Web Push.

- [x] Recipes to feature: r? @marco-c
  - [x] Simple Notification (#42)
  - [x] Payload (#43)
  - [x] Rich notifications (#54)
  - [x] Subscription management for multiple channels (#44)
  - [x] Quota (#47)
  - [x] Clients management (#46)
  - [x] Replace existing notification using a tag (#65)

**Comment by digitarald** [comment]
@zalun wanted to take a look at the recipes. Should we file a bug per recipe?

**Comment by marco-c** [comment]
Filed #42, #43 and #44 for now.

What do you mean by "rich notifications"? Notifications with icons, images, etc.?

**Comment by marco-c** [comment]
I've also filed #46, which aims to show `clients.openWindow` and `focus`.

**Comment by marco-c** [comment]
https://hacks.mozilla.org/2015/12/web-push-notifications-from-irssi/
