### ISSUE TITLE
Blog: At your service for more than just appcache

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#13]
More than ~~words~~ *appcache*!  Thinking beyond offline when cooking with Service Workers.

Recipes to be defined by @lodr

**Comment by marco-c** [comment]
Duplicate of #12?

**Comment by delapuente** [comment]
I think so. Reopen if not.

**Comment by digitarald** [comment]
This would also cover the blog post. Any takers on writing about the offline use cases?

**Comment by delapuente** [comment]
Oh, perfect. I'm taking this bug. Could you give me access to Moz Hacks?

**Comment by digitarald** [comment]
:tada: @delapuente! I checked with the hacks team: step 1 is draft (gdocs works great as it has comments and revisions). step 2 is scheduling a publishing date.

**Comment by marco-c** [comment]
https://hacks.mozilla.org/2015/12/beyond-offline/
