### ISSUE TITLE
MessageRelay demo doesn't work in Chrome

### ISSUE THREAD

**Issue by dbialer** [mozilla/serviceworker-cookbook#137]
I can't figure out how to make this demo work.  There doesn't seem to be a way to post the message.  Or for me it isn't obvious.  Tried in Chrome 46.

**Comment by marco-c** [comment]
I'm going to look into this.

**Comment by marco-c** [comment]
We need to wait Chrome to support it:
https://code.google.com/p/chromium/issues/detail?id=543198
https://code.google.com/p/chromium/issues/detail?id=549346
