### ISSUE TITLE
Bug: Docco does not generate documentation if a recipe contains a folder

### ISSUE THREAD

**Issue by franciov** [mozilla/serviceworker-cookbook#14]
It seems that docco, the tool for generating documentation when running `gulp build-docs`, does not work properly if a recipe contains a folder: the js files after the folder, in a lexical order, are not processed.

I had to remove the folder in my recipe to make it work: https://github.com/mozilla/serviceworker-cookbook/commit/db6567d83ea9d78fa9e7abfd76880cb4db301e78

```
$ npm -v
2.14.7
$ node -v
v4.2.1
```

**Comment by digitarald** [comment]
Not sure if we need to fix this. Having flat recipes seems a much more accessible and force you to simplify.

**Comment by delapuente** [comment]
But what if you try to hide some details, for instance, in the #23 recipe about caching the contents from a ZIP file, I want to hide the `zip.js` library under the `lib` directory. I really think we should agree on some patterns for recipes but I think we should fix this as well. I'm providing a PR to solve it.
