### ISSUE TITLE
Force redirect from heroku to official domain

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#146]
We got a few [links](http://www.brucelawson.co.uk/2015/progressive-web-apps-ready-for-primetime/) floating around to the herokuapp URL.

Lets do a 301 redirect if the domain is localhost (or `PRODUCTION` in `NODE_ENV`?).

**Comment by fbender** [comment]
This is also true for the MozHacks post, at least the last time I checked. You might want to update that (whether you add the redirect or not).

**Comment by darkwing** [comment]
I've updated the Moz Hacks post to reflect the new URLs.  Thanks for the shout @fbendr!

**Comment by darkwing** [comment]
Fixed this a few days ago
