### ISSUE TITLE
there are some problems when i run npm install 

### ISSUE THREAD

**Issue by toxic-johann** [mozilla/serviceworker-cookbook#179]
i fork it and i run npm install
but it seems some problem happen
![image](https://cloud.githubusercontent.com/assets/2577157/11946390/385ba362-a895-11e5-9302-6599cb00314d.png)
i can't find this dev.
is it necessary or how can i solve it?

**Comment by toxic-johann** [comment]
i find what the problem is.because i can't not find alrra/travis-scripts in cnpm.i change into npm and solve this problem

**Comment by marco-c** [comment]
I can't reproduce the problem.
We don't really need that dependency though, so I submitted #180 to remove it.

**Comment by toxic-johann** [comment]
ok,thanks a lot~
