### ISSUE TITLE
help my code reading!!!

### ISSUE THREAD

**Issue by lv7777** [mozilla/serviceworker-cookbook#184]
https://serviceworke.rs/api-analytics_service-worker_doc.html

> self.onfetch = function(event) {
>  event.respondWith(log(event.request).then(fetch));
> };

in

> .then(fetch)

What is this code doing ?
I assume this code is request to "api/quotations",right?

**Comment by marco-c** [comment]
`log(event.request)` logs the request and returns a Promise that resolves to the request.
Once the promise is resolved, `fetch` is called with the request.

A more verbose equivalent would be:
```JavaScript
log(event.request)
.then(function(request) {
  return fetch(request);
})
```
