### ISSUE TITLE
immediate-claim/service-worker.js should set max-age 0

### ISSUE THREAD

**Issue by wanderview** [mozilla/serviceworker-cookbook#201]
Currently the immediate-claim/service-worker.js is being served with this header:

  Cache-control: public, max-age=7200

This means when someone runs the demo and clicks the "update" button, they will most likely not see the service worker update.  The browser will check the script to see if its a byte-for-byte match with the installed worker.  Since its in the http cache it will almost always be the same.

To make this demo effective for people visiting the site we should set the max-age to 0 for this script.  (And probably all service worker scripts on this demo site, to be honest.)

**Comment by digitarald** [comment]
Good catch. I will add a custom rule for service worker files.

**Comment by darkwing** [comment]
My PR for this was merged.
