### ISSUE TITLE
"Offline Fallback" demo not accessible offline

### ISSUE THREAD

**Issue by anaran** [mozilla/serviceworker-cookbook#217]
[Offline Fallback Demo](https://serviceworke.rs/offline-fallback_demo.html)
only caches 
[oninstall] Cached offline page "https://serviceworke.rs/offline-fallback/offline.html"

The demo itself, however, is not accessible while offline since it is not getting cached.

Using this demo in a firefox os bug report leads to some awkward recipe as a consequence:

[1255803 – "_URL_ requires an internet connection" dialog blocks access to cached web app](https://bugzil.la/1255803)

Wouldn't it be more useful to cache the demo entry page instead?

**Comment by delapuente** [comment]
Although I admit this is weird, this specific demo should be run in isolation. Filed #277
