### ISSUE TITLE
Recipe: API analytics

### ISSUE THREAD

**Issue by delapuente** [mozilla/serviceworker-cookbook#22]
Perform API usage logging without interfering with the UI layer by adding a service worker to gather the usage and use the `sync` API to upload gathered data from time to time.

**Comment by darkwing** [comment]
Excuse my ignorance but what `sync` API are you referring to?

**Comment by digitarald** [comment]
@darkwing https://slightlyoff.github.io/BackgroundSync/spec/

**Comment by delapuente** [comment]
I'm going to implement this without sync API and update once we have this API available.

**Comment by digitarald** [comment]
Would it make sense to polyfill the background sync? I guess though a service worker has no idea when its woken up or dies, so it would be hard to control.

**Comment by delapuente** [comment]
I think the recipe is useful as it is, when we have sync API ready we can provide another recipe with that or a version two of this one or even a _mixture_ between both of them.
