### ISSUE TITLE
page to help people convert AppCache into a service worker

### ISSUE THREAD

**Issue by clarkbw** [mozilla/serviceworker-cookbook#229]
AppCache will soon be disabled in Firefox and service workers are supported and provide a better caching opportunity anyway.

I thought the cookbook could provide a simple page to take an AppCache file (or perhaps a URL where it would find the manifest file from a site) then display what the required code would be to reproduce the caching service worker; HTML changes + JS code for a sample service worker.

There is already some code out there to parse the manifest files: https://www.npmjs.com/package/parse-appcache-manifest

Disable AppCache: https://bugzilla.mozilla.org/show_bug.cgi?id=1237782

**Comment by digitarald** [comment]
Also want to throw in an experiment: could a drop-in library that gets pointed to an appcache file do something similar without a build step?

**Comment by digitarald** [comment]
@miketaylr mentioned that a shim or drop in library is on top of web compat's mind and we might be able to help using our service worker expertise. @delapuente, @marco-c could you do some exploration here to give a recommendation how feasible this would be?

**Comment by jeffposnick** [comment]
FYI—I (as a member of Google's Web DevRel team) have been implementing a helper for the runtime conversion scenario, with code at https://github.com/jeffposnick/appcache2serviceworker/pull/1.

The plan is to release it in a more permanent home, but it needs tests, docs, and a bit of refactoring first.

I don't point that out to discourage any efforts that the Mozilla folks might put into implementing something similar, of course.

**Comment by marco-c** [comment]
@jeffposnick I don't see any reason why we would duplicate our efforts.

**Comment by clarkbw** [comment]
@jeffposnick this is great!  Looks like similar goals, how can we help?

**Comment by jeffposnick** [comment]
:smile: 

While I've been relying on the extremely capable @jakearchibald for feedback on the code so far, feel free to take a look at what's there and, if you're so inclined, try following the examples from the demo/ directory against a test deployment of any real-world App Cache examples you have. (Apologies that there's no formal docs for using it yet.)

Any feedback is welcome on that PR, and I can update this thread when we have the code in a more permanent home.

**Comment by addyosmani** [comment]
Hey folks (@clarkbw, @marco-c). If you have time, we would love to get more feedback on Jeff's conversion library before we move it to a new repo. Do you think you might have time to take a look over it?

**Comment by delapuente** [comment]
[Comment 44 at bugzilla bug 1237782](https://bugzilla.mozilla.org/show_bug.cgi?id=1237782#c44) points to https://github.com/kenchris/jakecache

**Comment by delapuente** [comment]
Anyway, I'm taking a look at @jeffposnick PR

I'm thinking if more than a polyfill, we could use a conversion to pure sw, to preserve AppCache behavior without imitating it which could lead to better adoption.

**Comment by delapuente** [comment]
Done, I left my comments on [@jeffposnick PR](https://github.com/jeffposnick/appcache2serviceworker/pull/1).

**Comment by clarkbw** [comment]
We can probably close this issue out now.  We might want to open another issue for pointing to useful AppCache to ServiceWorker utilities but I think the original intent is well covered well by  https://github.com/kenchris/jakecache and the work going into jeffposnick/appcache2serviceworker#1
