### ISSUE TITLE
Recipe: download a zip and cache its contents

### ISSUE THREAD

**Issue by delapuente** [mozilla/serviceworker-cookbook#23]
With the use of 3rd party libraries such as [zip.js](https://gildas-lormeau.github.io/zip.js/), the Service Worker can use other workers to decompress a zip in the client and use it as source for caching off-line content. For instance, [downloading GitHub provided zip for a branch](http://stackoverflow.com/questions/13636559/how-to-download-zip-from-github-for-a-particular-commit-sha#answer-13636954).

**Comment by wfwalker** [comment]
could this be a way to "install" Firefox OS packaged apps, at least unprivileged ones?

**Comment by delapuente** [comment]
For unattended solutions, we could process the application to add an install UI registering a service worker to do this or decompress the application, serve it statically in a FQDN and provide some kind of `_install.html` UI to allow registering the SW in charge of download the zip. Does it make sense, @wfwalker ?

**Comment by digitarald** [comment]
throwing in my ideas to see if I understood correctly:

- each app would run on its own domain
- opening `/index.html` would install the sw, which fetches the zip and puts its content into cache. When the sw activates, the client refreshes the page
- further requests to `/index.html` are served from the package content.

**Comment by delapuente** [comment]
But to not interfere with the application structure, we could redirect to `_install.html` first. Then register the SW and install all the staff and finally leave some kind of mark (webstorage, cookie or whatever) to detect the application is installed next time and redirect to the `launch_path` specified in the manifest. We could even make the SW to answer with a permanent redirection to `launch_path` for `_install.html` once installed.
