### ISSUE TITLE
Document technical specs of running app

### ISSUE THREAD

**Issue by darkwing** [mozilla/serviceworker-cookbook#25]
I installed a few different versions of Node.js before finding a version that supported `String.prototype.startsWith`.  Having a tech spec doc would be helpful for working within this repo.

**Comment by digitarald** [comment]
I am just spoiled by babel adding polyfills ;) . We should remove node 4 dependencies to make it more accessible.

**Comment by darkwing** [comment]
Going to close this as we've not seen other problems here.
