### ISSUE TITLE
URL.createObjectURL is not a function on Request Deferrer Demo 

### ISSUE THREAD

**Issue by sombodi** [mozilla/serviceworker-cookbook#263]
We are getting this error when turning internet connection back on, and the system tries to sync, 
on the demo  at localforage.js:1276 Uncaught TypeError: URL.createObjectURL is not a function

Where is URL defined? We can't find it either. 

Thanks

**Comment by marco-c** [comment]
It's a global object:
https://developer.mozilla.org/en-US/docs/Web/API/URL
https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

**Comment by marco-c** [comment]
In which browser and which version are you seeing this error?

**Comment by delapuente** [comment]
It seems that [`createObjectURL` must not be exposed inside a Service Worker](https://github.com/w3c/ServiceWorker/issues/688) environment. Let's close it here and open a bug in localForage.
