### ISSUE TITLE
Receive Push Payload Demo stopped working

### ISSUE THREAD

**Issue by arcturus** [mozilla/serviceworker-cookbook#265]
Right now the following recipe is not working:

https://serviceworke.rs/push-payload_demo.html

When pressing the button to send the notification, after a while the heroku app return a 503 error.

/cc @marco-c @delapuente

**Comment by marco-c** [comment]
It's working for me in Nightly, but anyway I think we should update the examples with the latest version of the `web-push` library.

**Comment by arcturus** [comment]
Oh sorry my fault, tried this with stable, 50.1.0
