### ISSUE TITLE
[cache-then-network] Don't bust cache if not necessary

### ISSUE THREAD

**Issue by TimAbraldes** [mozilla/serviceworker-cookbook#27]
Feature detect whether cache options are available in the Fetch API by checking whether `Request.prototype.cache` exists.

If it exists, we pass 'no-cache' as the cache option so we shouldn't need to use a cache-busting URL param

**Comment by marco-c** [comment]
Looks like it is available everywhere: https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

**Comment by marco-c** [comment]
So I guess we can't use it to feature detect? Since https://bugzilla.mozilla.org/show_bug.cgi?id=1120715 is still open.

**Comment by TimAbraldes** [comment]
Yeah it would seem that feature detection isn't going to help us here
