### ISSUE TITLE
Broaden the opening description so it's clear Service Workers are for more than just apps

### ISSUE THREAD

**Issue by jensimmons** [mozilla/serviceworker-cookbook#280]
You start by saying:

The Service Worker Cookbook is a collection of working, practical examples of using service workers in modern web apps.

But Service workers can be used for great affect for many more projects than the ones that are considered "an app". I know Google wants to promote the concept of a "PWA" and define a specific formula for making a PWA... but I hope Mozilla can have a broader vision for the whole web, and how any of these open technologies can be used in a range of projects. 

Service Workers are for more than just apps. Let's say so.

**Comment by marco-c** [comment]
I'm fine with changing the description, but I have no ideas on how to improve it.

cc @delapuente

**Comment by delapuente** [comment]
Btw, thank for the heads up.
