### ISSUE TITLE
Catch push event in angular app

### ISSUE THREAD

**Issue by narendrasinghrathore** [mozilla/serviceworker-cookbook#282]
How can i catch the push event in service worker in angular app. Is there any way to $watch on "push" event of service worker...?

**Comment by amitparrikar** [comment]
Service Worker is totally different entity, it has nothing to do with AngularJS. neither you can watch on any service worker variables.

Solution:

- Write a AngularJS Service which listen on all the **message** event from your service worker.
- Now this service will be your contact person to your service worker. Make it like a utility service for Service Worker.
- Whenever service worker pushes any notification, it will inform your service, and then you can broadcast it wherever you require(or use a publisher subscriber model).

**Comment by narendrasinghrathore** [comment]
@amitparrikar  Can you share some code for creating service of service worker in angularjs ?
Thank you.

**Comment by marco-c** [comment]
This is not an issue.
