### ISSUE TITLE
Where do I retrieve an GCM_API_KEY?

### ISSUE THREAD

**Issue by hirasso** [mozilla/serviceworker-cookbook#283]
The title says it all – sorry if the question is dump ?:/
I *do* need one on the server side, right?

**Comment by marco-c** [comment]
It's not strictly needed. New versions of Chrome support VAPID and don't need a GCM API key.

**Comment by hirasso** [comment]
Thanks for your response! So – where do I get those VAPID keys?

**Comment by marco-c** [comment]
You genereate them yourself, look at the documentation of the web-push library: https://github.com/web-push-libs/web-push.
