### ISSUE TITLE
The domain serviceworke.rs has expired

### ISSUE THREAD

**Issue by Genteure** [mozilla/serviceworker-cookbook#286]
```
$ whois serviceworke.rs

Domain name: serviceworke.rs
Domain status: Expired, clientUpdateProhibited
Registration date: 16.11.2015 19:06:36
Modification date: 07.04.2017 11:52:15
Expiration date: 16.11.2017 19:06:36
Registrar: NINET Company d.o.o.


Registrant: Harald Kirschner


DNS: marek.ns.cloudflare.com -
DNS: kia.ns.cloudflare.com -


Administrative contact: Harald Kirschner

Technical contact: Bratislav Krstic, NINET Company d.o.o.
Address: Bul. Nemanjica 25, TC Zona 3 lok. K6, Nis, Serbia
```
_Oops..._

**Comment by marco-c** [comment]
CC @digitarald

**Comment by anisse** [comment]
Indeed, it also means broken links in MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Push_API

**Comment by mrbinr** [comment]
Some parts seems to be accessible using https://web.archive.org/web/20171109215500/https://serviceworke.rs/
i hope it will be online soon ...

**Comment by digitarald** [comment]
Cloudflare thought that the nameservers got broken; which seems all correctly configured. It is currently re-fetching them, which should fix the issue. Will report back when my manic refreshing leads to a result.

**Comment by peterjanes** [comment]
The whois record still says the domain has expired, which may be the core issue.

**Comment by digitarald** [comment]
True. The interface is broken then. Expiration date is correctly shown as Nov 16th, so I just renewed. I am now waiting for the change to be reflected.

**Comment by digitarald** [comment]
Confirmed fixed.
