### ISSUE TITLE
The GCM API Key should be a non-empty string or null.

### ISSUE THREAD

**Issue by rathorebs** [mozilla/serviceworker-cookbook#288]
Hi Team,
I'm facing following error. 

![issue](https://user-images.githubusercontent.com/9293248/33720471-0bb121c8-db8a-11e7-86aa-c3db1eebf3f3.jpg)

**Comment by lechidung** [comment]
me too!

**Comment by marco-c** [comment]
You need to set the `GCM_API_KEY` environment variable. If you are testing with recent versions of Firefox/Chrome you don't actually need it, so you can set it to a fake value (e.g. `set %GCM_API_KEY%=ciao`).

**Comment by marco-c** [comment]
It should be no longer required now.
