### ISSUE TITLE
Not working in chrome localhost

### ISSUE THREAD

**Issue by rravithejareddy** [mozilla/serviceworker-cookbook#289]
It's working in firefox but did'nt worked on chrome localhost(not secured), i am getting 500 internal error. it worked on chrome when i see in this link https://serviceworke.rs/. do need to include GCMapikey to work on chrome ?

**Comment by rravithejareddy** [comment]
It's working in firefox but did'nt worked on chrome localhost not secured, it worked on chrome when i see in this link https://serviceworke.rs/. do need to include GCMapikey to work on chrome ?

**Comment by marco-c** [comment]
Yes, I think you need a GCM API key. Unfortunately the project hasn't been updated to use VAPID.

**Comment by slokhorst** [comment]
Fixed by #294
