### ISSUE TITLE
TypeError: ServiceWorker script encountered an error during installation.

### ISSUE THREAD

**Issue by nvtuan305** [mozilla/serviceworker-cookbook#291]
I have tested https://serviceworke.rs on the Google Chrome v50+ and everything is working but I will get the error below on Firefox 44, 45, 46, 52, latest Firefox (version 57.0.4 64 bit) when call `navigator.serviceWorker.register('./service-worker.js')` function.
> TypeError: ServiceWorker script at https://serviceworke.rs/push-payload/service-worker.js for scope https://serviceworke.rs/push-payload/ encountered an error during installation.

I have opened a new question on Stackoverflow at [here](https://stackoverflow.com/questions/48295748/firefox-typeerror-serviceworker-script-encountered-an-error-during-installation)

**Comment by tupham2006** [comment]
Hello. Do you use Linux? I have same problem when use Linux but It works fine on window

**Comment by marco-c** [comment]
CC @wanderview

**Comment by nvtuan305** [comment]
@tupham2006 I'm using Ubuntu 16.04 LTS. I will check it on Windows. Do you have any solutions to fix this issue on Linux?

**Comment by wanderview** [comment]
How are you using to serve the script and what is its Content-Type header?

**Comment by thasmo** [comment]
@wanderview, I'm encountering the same issue with Firefox Quantum Developer Edition 59.0b13 (64-Bit) on Windows 10 Pro.

**Comment by wanderview** [comment]
I need better steps to reproduce.  Please spell exactly which page is being loaded, etc.

Also, do you have any non-standard cookie preferences?  For example, blocking cookies or configuring cookies to be deleted when the browser exits?  These can disable service workers.

**Comment by thasmo** [comment]
@wanderview, on https://serviceworke.rs/push-payload/ I get `TypeError: ServiceWorker script at https://serviceworke.rs/push-payload/service-worker.js for scope https://serviceworke.rs/push-payload/ encountered an error during installation.`.

Network log:
* 200 GET /push-payload/
* 200 GET index.js

Calling `https://serviceworke.rs/push-payload/service-worker.js` directly gives `200 GET service-worker.js`, and the headers are:
```
HTTP/2.0 200 OK
access-control-allow-headers: Origin, Content-Type, Accept
access-control-allow-origin: *
cache-control: public, max-age=7200
cf-cache-status: MISS
cf-ray: 3f460ec8f96e8ca6-VIE
content-encoding: br
content-type: application/javascript; charset=UTF-8
date: Wed, 28 Feb 2018 20:15:46 GMT
etag: W/"2b9-1616e050fe8"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Wed, 28 Feb 2018 22:15:46 GMT
last-modified: Wed, 07 Feb 2018 02:08:01 GMT
server: cloudflare
strict-transport-security: max-age=2592000
vary: Accept-Encoding
via: 1.1 vegur
x-content-type-options: nosniff
X-Firefox-Spdy: h2
x-powered-by: Express
```

I'm not aware of any special cookie settings. Where would I look that up?

**Comment by wanderview** [comment]
Hmm, I can't reproduce.

![screenshot 2018-02-28 15 19 52](https://user-images.githubusercontent.com/1256526/36811202-f78c772c-1c9a-11e8-9e2f-bbcddb8bda8e.png)

Can you go to about:support, click "copy text to clipboard", and paste here?

**Comment by wanderview** [comment]
Oh, also, did you ever open this same profile in multiple versions of firefox?  For example, in both release and nightly, etc?

**Comment by thasmo** [comment]
@wanderview, I do only have Firefox Developer edition installed but I did swap from the standard edition quite some time ago. I'm going to check if a different profile behaves different.

**Comment by wanderview** [comment]
FWIW, you should always use a separate profile for each channel (release/beta/dev-edition/nightly).  We're working on making it work like that out-of-the-box, but its not ready yet.

**Comment by thasmo** [comment]
I'm using another channel at work with the same profile, could that be the problem? (Even when not on the same machine?)

**Comment by wanderview** [comment]
The profile is local to a machine unless you are somehow sync'ing the profile between them through some external means.

A good first step to test if the profile is the problem is to test on a new profile.  You can go to about:profiles, click "create new profile", and then "launch profile in new browser".

**Comment by thasmo** [comment]
Created a new profile; the problem is gone. Thanks a lot, @wanderview!

**Comment by nvtuan305** [comment]
It worked after I go to `about:support` and click `Refresh Firefox`. Thank a lot, @wanderview

**Comment by BernardA** [comment]
@nvtuan305  The solution above did not work for me. I have both Firefox, which I use for my personal stuff and FirefoxDeveloperEdition, used for development, of course.
I checked and I do have 2 profiles.
Service worker will give above error on FDE but will work fine on the 'regular' Firefox.
Should I open another issue?
Pls. advise.

**Comment by nvtuan305** [comment]
@BernardA I think that you can try to:
1. Refresh profile on both version:
> It worked after I go to about:support and click Refresh Firefox.

2. Reinstall both version then create new profile for Firefox Developer Edition. Each channel should use separate profile.
> A good first step to test if the profile is the problem is to test on a new profile. You can go to about:profiles, click "create new profile", and then "launch profile in new browser".

**Comment by BernardA** [comment]
Thanks @nvtuan305, it did work when I created a new profile and opened the FDE from there. But the issue persisted when opening FDE directly.  It took me a while to find out that about:support should be entered on the address bar, but once I found it and refreshed FDE things went fine.

**Comment by victorwealth** [comment]
Yes refresh firefox fixed the issue for me too. Thanks @nvtuan305 and @wanderview.

**Comment by mum-viadee** [comment]
Refreshing firefox fixed the issue for me, too.

**Comment by br4nnigan** [comment]
I also experience the bug. I installed DevEdition and used sync to get my "work profile" which might have been used on another FF (channel) at one point. 

So what now, I can basically scrap the profile because it is corrupted? There's stuff in it (which is the point of profiles). How can I mitigate my stuff to a not corrupted profile?
