### ISSUE TITLE
Got 404 of URL 'register' and 'unregister' in 'Push Subscription'

### ISSUE THREAD

**Issue by red0whale** [mozilla/serviceworker-cookbook#298]
In the '[Push Subscription](https://serviceworke.rs/push-subscription-management.html)' recipe, where is the url '_register_' and '_unregister_' in the first parameter of fetch API? I got 404 error.
By the way, my server uses PHP.

![](https://uploads.disquscdn.com/images/dd2e65564a44fbcffe5d50f2b9c3890412e51c16c48ce8d1302e5436dd3d52f1.png)

![](https://uploads.disquscdn.com/images/5ca4df7aad89e32d6984a7f6e468150205d6072ae7e7f3c87ac884cb54b1fb1f.png)

**Comment by slokhorst** [comment]
These examples won't work with a PHP server. You need to run the Node.js server code we supply (see [README.md#how-to-contribute](https://github.com/mozilla/serviceworker-cookbook/blob/master/README.md#how-to-contribute) for how to run it), or reimplement [the corresponding server.js](https://github.com/mozilla/serviceworker-cookbook/blob/master/push-subscription-management/server.js) yourself in PHP.
