### ISSUE TITLE
Provide annotated sources for recipes

### ISSUE THREAD

**Issue by delapuente** [mozilla/serviceworker-cookbook#30]
Using docco we could extract an eye-catcher documentation in addition to the sources on GitHub.

**Comment by delapuente** [comment]
@darkwing @digitarald what do you think?

**Comment by digitarald** [comment]
Agreed and done :) https://serviceworker-cookbook.herokuapp.com/docs/auto-claim/service-worker.html

**Comment by digitarald** [comment]
Closing if nothing else is covered by this. We definitely need to add more docs to some recipes, part of best practices.

**Comment by zalun** [comment]
The link s broken - Cannot GET /docs/auto-claim/service-worker.html

**Comment by darkwing** [comment]
https://serviceworker-cookbook.herokuapp.com/docs/immediate-claim/service-worker.html

**Comment by delapuente** [comment]
I'm closing this as the functionality is added but we need better support from the `index.html` page. Let's file different issues for this.
