### ISSUE TITLE
Change samples to subscribe when serviceWorker.ready resolves

### ISSUE THREAD

**Issue by aliams** [mozilla/serviceworker-cookbook#302]
The code samples should be changed to only call the subscribe() function when the serviceWorker.ready promise resolves.

#170, though similar, discussed how to ensure the page was controlled by the service worker which required the use of the controllerchange event.

For push, we do not need to wait for the page to be controlled, but rather we just need the service worker registration to have an active service worker (i.e. when the serviceWorker.ready promises resolves).

**Comment by slokhorst** [comment]
Sounds good. Can you verify that #303 fixed things in Edge?

**Comment by aliams** [comment]
That was fast! This looks good to me. It seems that the only issue now is the TTL. WNS (windows notification service) doesn't seems to like the value 0. If I set the value to 1 it seems to all be working.

**Comment by slokhorst** [comment]
Sounds reasonable to set the default to something other than 0, as that is known to discard the message immediately:
https://blog.mozilla.org/services/2016/02/20/webpushs-new-requirement-ttl-header/

I'm not sure if 1 second is the best default or we should use a higher value. I've set it to 1 in the PR for now: df4c360e3d0be47dee0a72ebcc687b9624e934ec

**Comment by slokhorst** [comment]
Hm, according to the [spec](https://webpush-wg.github.io/webpush-protocol/):

> A Push message with a zero TTL is immediately delivered if the user agent is available to receive the message.

So it sounds like this is an issue with Edge.

Although I guess it couldn't hurt to set the default value to something higher than 0.

**Comment by aliams** [comment]
Yeah, agreed. What if we set the default to match what the web-push library uses? It has the default TTL of four weeks (2419200).

**Comment by slokhorst** [comment]
Using 2419200 sounds reasonable, although it is a bit arbitrary.

We could also completely omit the TTL input box like in some of the other push recipes, and implicitly use the library's default, as I'm not sure how useful it is to have it as an user-editable field.

Or, most simple, just leave it as-is and maybe add a note that WNS/Edge is picky about a value of zero?

@marco-c what do you think?

**Comment by marco-c** [comment]
Let's open a new issue about the 0 TTL. I agree it's not that useful to have it in all recipes, but I'd like to have it at least in one (where we also say that Edge is picky about 0, so our "readers" will know and not run into problems).
Maybe we could remove it from all and create a new recipe just about TTL.
