### ISSUE TITLE
Add descriptions of recipes along with use case

### ISSUE THREAD

**Issue by dbialer** [mozilla/serviceworker-cookbook#31]
What is the recipe?  Who is it for?  What problem does it solve?
It would be good to document and describe these on the home page?

**Comment by digitarald** [comment]
Yes, agreed. We need to describe best practices and requirements and check them against each recipe.

**Comment by darkwing** [comment]
Good point @dbialer .  Maybe we add tags as well, like "claim", "offline", "performance", etc.

**Comment by marco-c** [comment]
We could add a short description in the main README and add a detailed README for each recipe.

**Comment by digitarald** [comment]
We mostly got there, lets make sure we got use cases in a follow up
