### ISSUE TITLE
Push Simple demo stopped working

### ISSUE THREAD

**Issue by rayfoss** [mozilla/serviceworker-cookbook#311]
https://serviceworke.rs/push-simple.html

Snarky comments aside:
![screen shot 2018-08-14 at 9 06 33 am](https://user-images.githubusercontent.com/876076/44096638-60c8a434-9fa1-11e8-82c0-11d4c0e1f6bd.png)

**Comment by marco-c** [comment]
It seems to be working again now, maybe it was a temporary issue.
