### ISSUE TITLE
serviceworke.rs website offline

### ISSUE THREAD

**Issue by FbN** [mozilla/serviceworker-cookbook#314]
serviceworke.rs can’t be reached

**Comment by mykmelez** [comment]
@digitarald I suspect this is because the domain name registration has expired:

> Is this why the site is down? I think it should display something a bit more obvious...

No, I don't think anything has been done here yet that would cause the site to go down. However, I previously noted that the domain name registration expires on November 16, and I don't find it anymore:

```
> dig serviceworke.rs

; <<>> DiG 9.10.6 <<>> serviceworke.rs
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41277
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;serviceworke.rs.		IN	A

;; Query time: 124 msec
;; SERVER: 192.168.43.99#53(192.168.43.99)
;; WHEN: Mon Nov 19 09:02:33 PST 2018
;; MSG SIZE  rcvd: 33
```

**Comment by digitarald** [comment]
I renewed serviceworke.rs, will take a bit to go live again. We have another year to handle migration in #312.

**Comment by andyautida14** [comment]
The domain name registration expired again

**Comment by marco-c** [comment]
@andyautida14 follow-up discussion in #312.
