### ISSUE TITLE
Recipe: Cache no-cors response

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#32]
Idea for example use case: Audio from external server that doesn't have HTTPS.

That should show a reduced version of what https://github.com/mozilla/high-fidelity/ needs for @zalun, right @delapuente ?

**Comment by delapuente** [comment]
I'm afraid I missunderstood mixed-content with access policy. Let's review the SW spec and think a little bit more about it.

**Comment by delapuente** [comment]
Well, this is what I discovered about mixed content by reading [specs](https://w3c.github.io/webappsec-mixed-content/) again. There is a concept about a passthrough request. A [passthrough](https://w3c.github.io/webappsec-mixed-content/#passthrough-request) request is a request originated by a fetch inside a service worker using a request originated in a client window. Something like:

```js
self.onfetch = function (event) {
  return event.respondWith(fetch(event.request));
}
```
According to the [blocking rules for requests](https://w3c.github.io/webappsec-mixed-content/#should-block-fetch), a request to a non https should be allowed if it is a passthrough request. Once the request is allowed it remains for the response to be allowed as well. If the request is made with `{ mode: 'no-cors' }` the response to the fetch is a [filtered opaque response](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque) and according to the [blocking rules for responses](https://w3c.github.io/webappsec-mixed-content/#should-block-response) it should be allowed.

I shared this @zalun and he did a nice demo with https and http / cors and no-cors requests. According to the results, not even the request is allowed so we think that is a bug. I will be checking these topics with baku & bkelly this Monday.

By the way, I think the same demo @zalun did is good enough to cover this recipe. If not, I can still take it. What do you think?

**Comment by marco-c** [comment]
I did something similar to cache images from trakt.tv (that were served without CORS headers): https://github.com/marco-c/watchy/blob/234b97ef06cfd6fd5a6e2620746840683bad6244/app/controllers/series-new.js#L116

**Comment by delapuente** [comment]
I see. Anyway, `no-cors` is the default option for mode but I think it's good to make it explicit.

**Comment by delapuente** [comment]
Well, checked with Ben Kelly. This is a well known bug. It is related to issue whatwg/fetch#70 and [bug 1183625](https://bugzilla.mozilla.org/show_bug.cgi?id=1183625) and you can find very similar concerns about [our problems with high-fidelity](https://aerotwist.com/blog/cors-for-concern/). Summarizing, the problem is we can not warn the user about mixed content if we don't have UX to show the warning (which is what the former bug and issues are about). So, right now, the browser simply rejects _mixing content_.

**Comment by darkwing** [comment]
^^ @digitarald Shall we take this out of v1 milestone due to browser bug?

**Comment by digitarald** [comment]
@darkwing, yes, totally makes sense!

I wonder how we can better document this behaviour, so others don't struggle? We might we land it and put it under an "Edgecases" category. @zalun had a good example of various requests succeeding and failing.

**Comment by zalun** [comment]
It is in cookbook - https://serviceworke.rs/fetching.html

**Comment by marco-c** [comment]
Should we close this?

**Comment by digitarald** [comment]
+1
