### ISSUE TITLE
Service worker expiration

### ISSUE THREAD

**Issue by TomPradat** [mozilla/serviceworker-cookbook#327]
This is not exactly an issue, but i've never been able to get an answer on stackoverflow.

I was wondering if the service worker expires in a browser. I couldn't find anything about it.

My problem is the following (hypothetical) :

I had a website with a service-worker that caches the static files and thus allow for offline usage. I decided to update my website and remove the service worker. The issue is that I always get the first version of my website as the previous service-worker has cached everything.

So I was wondering if the service-worker will expire to let me see my new website.

**Comment by slokhorst** [comment]
I'm not sure if the service worker will ever expire, but it will be updated by the browser at least every 24 hours. See [this StackOverflow question](https://stackoverflow.com/q/38843970/1427212) for more info.

If you want to remove your service worker, you should replace the file on the server with an empty file, that way the browser will replace the service worker with an empty one and the caching will be disabled. Note that *removing* the service worker file on the server [does not work](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates):
"If your new worker has a non-ok status code (for example, 404), fails to parse, throws an error during execution, or rejects during install, the new worker is thrown away, but the current one remains active."

**Comment by TomPradat** [comment]
Yeah that's what I though. IMO this is a big problem :

What if you buy a domain name (that previously had a website with a service worker) ? That means the people that went to the old website would never see your new website and you'll never know about it...

And the users would have a broken website until they clear the service worker (which is more complicated than just clearing website cache)

**Comment by slokhorst** [comment]
If you know the location of the previous service worker, you could place an empty file there to overwrite it. But yeah, I see your concern..

I think the best place for you to address this is the [w3c/ServiceWorker](https://github.com/w3c/ServiceWorker) repository. That is where the authors of the specification hang out. They would know for sure if there is some kind of expiration mechanism, and otherwise you could maybe convince them to add it to the specification.

**Comment by TomPradat** [comment]
I'll try to open a new issue, I already did here last year => https://github.com/w3c/ServiceWorker/issues/1366. Thanks for your time 👍
