### ISSUE TITLE
serviceworke.rs site is offline

### ISSUE THREAD

**Issue by izenski** [mozilla/serviceworker-cookbook#328]
ERR_NAME_NOT_RESOLVED message in the browser when I navigate to https://serviceworke.rs/

**Comment by riverside** [comment]
Domain expired on 2019-11-16 19:06:36

**Comment by vitorhsb** [comment]
Please fix this.

**Comment by marco-c** [comment]
CC @digitarald

**Comment by digitarald** [comment]
Looks like I missed the reminder on this due to travel. Just renewed the domain (will take a bit), good to see that the service is still being used – pardon the interruption!
