### ISSUE TITLE
Recipe: Push notification with quota management

### ISSUE THREAD

**Issue by marco-c** [mozilla/serviceworker-cookbook#47]

**Comment by digitarald** [comment]
Some best practices to demo:

Push server post quota:
- Back of when server rejects messages

Client quota:
- Always show a notification so quota gets reset
- Track how many notifications got received, shown or  clicked

**Comment by kitcambridge** [comment]
Hi! So, once [bug 1210211](https://bugzilla.mozilla.org/show_bug.cgi?id=1210211) lands, the quota will work like this: when a service worker receives a background push message, we'll start a timer for 3 seconds. Once the timer fires, we'll check if there are any visible notifications for the origin. If so, we won't reduce the quota.

One possible demo could encourage the user to close the page, then send a burst of messages (simulating a device that's just woken up from sleep) and display a single notification. You could also demo replacing existing notifications using the tag.

Another demo could show how to get a new subscription if the quota is exceeded. Unfortunately, the only way to know this is if the server rejects a message with a 404—we don't expose the quota via the DOM API. Once the user returns to the site, we'll fire the `pushsubscriptionchange` event.
