### ISSUE TITLE
Recipe: Offline status in frontend

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#5]
Per @wfwalker and his project https://github.com/wfwalker/mc-choir/ , it would be great to have an indication when the project is cached/*offlined* (`Dear user, you can now safely cut the cable!`). This is probably a mix of `claim` and listening to `controllerchange` in the frontend.

**Comment by darkwing** [comment]
I'd like to have a go at this, if that's cool.

**Comment by darkwing** [comment]
A few questions I've encountered as I've started this:

[ ] - Do you envision this using two service workers -- one for static assets for layout and then another for other media?

[ ] - Can we detect assets included within the HTML document itself, including `<img>`, `<link>`, via service worker?

[ ] - How does `controllerchange` factor into this?

**Comment by digitarald** [comment]
1. You can only have one active service worker
2. The assets are defined [within the service worker](https://github.com/wfwalker/mc-choir/blob/gh-pages/offline-worker.js#L30). The sw will only `activate` when all assets are cached
3. To get `controllerchange` the sw needs to claim the page, which by default only happens on refresh but which can be forced by calling `.claim()` (see [auto-claim](https://github.com/mozilla/serviceworker-cookbook/tree/master/auto-claim)).

**Comment by darkwing** [comment]
1.  Good to know
2.  Right, though they can be added as we go along with:  

```
self.addEventListener('fetch', function(event) {

  console.log('fetch!  ', event.request.url);

  event.respondWith(
    caches.match(event.request)
      .then(function(response) {
        // Cache hit - return response
        if (response) {
          console.log('Returning from ServiceWorker cache:  ', event.request.url);
          return response;
        }

        var fetchClone = event.request.clone();

        return fetch(event.request).then(function(response) {
          // Check if we received a valid response
          if(!response || response.status !== 200 || response.type !== 'basic') {
            return response;
          }

          var responseToCache = response.clone();

          caches.open(CACHE_NAME).then(function(cache) {
            console.log('Putting into SW cache: ', event.request.url);
            cache.put(event.request, responseToCache);
          });

          return response;
        });
      }
    )
  );
});
```

Right?

3.  So I'm confused as to the scope of this recipe.  Are we enhancing Bill's app, moving it over or...?  At face value this recipe seems incredibly simple but you've mentioned `controllerchange` and `claim()` so now I think I need more insight as to what's desired.

**Comment by darkwing** [comment]
This is set for PR review
