### ISSUE TITLE
Verify that everything works on https://serviceworke.rs/

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#85]
Put on your service worker rookie hat and take a deep dive at https://serviceworke.rs/.

r? @brendandahl @wfwalker @marco-c @zalun @darkwing @mykmelez @TimAbraldes

**Comment by wfwalker** [comment]
Message Relay README has an empty unordered list of Features and usage, and an empty "Use Case"


<img width="144" alt="cookbook" src="https://cloud.githubusercontent.com/assets/812428/11233957/1f366512-8d78-11e5-88cc-bbd9bb9d35bd.png">

**Comment by marco-c** [comment]
The API analytics doesn't seem to work for me.

**Comment by marco-c** [comment]
The `Offline Fallback` recipe doesn't seem to work for me. It always says I'm online and "Registered ServiceWorker" is "Did not register" and never changes.

**Comment by darkwing** [comment]
The `API Analytics` demo is functioning correctly but the demo iFrame is getting too small of a height so the link to the report isn't visible.

**Comment by darkwing** [comment]
I've got PRs to address all issues:

https://github.com/mozilla/serviceworker-cookbook/pull/98
https://github.com/mozilla/serviceworker-cookbook/pull/97
https://github.com/mozilla/serviceworker-cookbook/pull/96

**Comment by darkwing** [comment]
All addressed!
